### ISSUE TITLE
Trouble on wayland

### ISSUE THREAD

**Issue by Yamakaky** [slgobinath/SafeEyes#15]
https://aur.archlinux.org/packages/safeeyes/, last comment

**Comment by slgobinath** [comment]
@Yamakaky I will check it but this issue seems to be a common problem. See https://github.com/Alexey-Yakovenko/deadbeef/issues/1606, https://github.com/getlantern/lantern/issues/3618 and https://github.com/syncthing/syncthing-gtk/issues/73.

**Comment by slgobinath** [comment]
Fixed with https://github.com/slgobinath/SafeEyes/commit/24a0301847636acd61ce9b74fbcbac1ce94994d3. Tested on Fedora 25

**Comment by pedrolb** [comment]
Ubuntu 17.10 is still not out but i tried to use safe eyes on it, no success. I think its related to this bug, because when i run on xorg session it works.

Error i get when running safeeyes from terminal:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Xlib/xauth.py", line 42, in __init__
    raw = open(filename, 'rb').read()
FileNotFoundError: [Errno 2] No such file or directory: '/home/pedrolb/.Xauthority'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/safeeyes", line 9, in <module>
    load_entry_point('safeeyes==2.0.0', 'console_scripts', 'safeeyes')()
  File "/usr/lib/python3/dist-packages/safeeyes/__main__.py", line 132, in main
    safeeyes = SafeEyes(system_locale, config)
  File "/usr/lib/python3/dist-packages/safeeyes/SafeEyes.py", line 75, in __init__
    self.break_screen = BreakScreen(self.context, self.on_skipped, self.on_postponed, Utility.STYLE_SHEET_PATH)
  File "/usr/lib/python3/dist-packages/safeeyes/BreakScreen.py", line 47, in __init__
    self.display = Display()
  File "/usr/lib/python3/dist-packages/Xlib/display.py", line 80, in __init__
    self.display = _BaseDisplay(display)
  File "/usr/lib/python3/dist-packages/Xlib/display.py", line 62, in __init__
    display.Display.__init__(*(self, ) + args, **keys)
  File "/usr/lib/python3/dist-packages/Xlib/protocol/display.py", line 61, in __init__
    name, host, displayno)
  File "/usr/lib/python3/dist-packages/Xlib/support/connect.py", line 93, in get_auth
    return getattr(mod, modname).get_auth(sock, dname, host, dno)
  File "/usr/lib/python3/dist-packages/Xlib/support/unix_connect.py", line 116, in new_get_auth
    au = xauth.Xauthority()
  File "/usr/lib/python3/dist-packages/Xlib/xauth.py", line 44, in __init__
    raise error.XauthError('~/.Xauthority: %s' % err)
Xlib.error.XauthError: ~/.Xauthority: [Errno 2] No such file or directory: '/home/pedrolb/.Xauthority'

**Comment by slgobinath** [comment]
@pedrolb I remember I also got this problem.
Try to create an empty file using the following command and let me know the result:
```
touch ~/.Xauthority
```

**Comment by pedrolb** [comment]
@slgobinath It worked, I never tought it would be so easy :D Thanks

But the safe eyes is running with some problems in this new version. The system tray icon didn't show at first, and the text of the exercise isn't showing as expected. 

![foto](https://user-images.githubusercontent.com/1846630/31567091-284dd1e4-b044-11e7-9fef-b3e164b50f41.png)

I tried a purge and reinstall and now the plugin for system tray was ok (came as on) but the text still came as a variable name. But i am running it now :)

**Comment by pedrolb** [comment]
my bad, it wasn't a clean reinstall, i purged it again and this time removed the safeeyes folder from .config. Safe Eyes working as expected, thanks a lot 👍

**Comment by slgobinath** [comment]
@pedrolb that's my fault. I implemented to upgrade from the previous version which causes to this issue. Will fix it in the next release even though it is too late.

**Comment by pedrolb** [comment]
Well at least it seems like an easy fix. I think everybody who enjoys safe eyes can understand this little problem. Thanks for the help and for this really usefull program.
